fragment PageFields on Page {
  id
  data
  width
  height
  previewImages
  previewActions {
    primary {
      mode
      values {
        hotkeys
        changePage
        special_keys
        text
        settings {
          value
          setting
        }
      }
    }
    secondary {
      mode
      values {
        hotkeys
        changePage
        special_keys
        text
        settings {
          value
          setting
        }
      }
    }
  }
  createdBy {
    avatar
    displayName
  }
  name
  upvotes
  tags
}

query searchPages($searchTerm: String!, $before: String, $after: String) {
  searchPages(
    searchTerm: $searchTerm
    pagination: { before: $before, after: $after }
  ) {
    hasNext
    pages {
      ...PageFields
    }
  }
}

query me {
  user {
    id
    avatar
    displayName
  }
}

query myPages {
  myPages {
    ...PageFields
  }
}

query page($id: String!) {
  page(id: $id) {
    ...PageFields
  }
}

mutation pageCreate($input: PageCreateInput!) {
  pageCreate(input: $input)
}
